.\" Manpage for szserver..
.TH man 6 "15 May 2018" "1.0" "szserver man page"
.SH NAME
szserver \- Inicia un servidor para los szclient
.SH SYNOPSIS
szserver 
.SH DESCRIPTION
szserver es un programa que actua como servidor para una aplicacion que simula el mini-safari Pokemón
.SH OPTIONS
No Hay opciones adicionales
.SH SEE ALSO
szclient (6)
.SH BUGS
No hay conocidos
.SH AUTHOR
(diegofavela@.ciencias.unam.mx, 777coatl@ciencias.unam.mx, fernandofong@ciencias.unam.mx)
