.\" Manpage for szclient.
.TH man 6 "15 May 2018" "1.0" "szclient man page"
.SH NAME
szclient \- Inicia una cliente para conexion a szserver
.SH SYNOPSIS
szclient [USUARIO] [DIRECCION IP DE SERVIDOR] [PUERTO: 9999]
.SH DESCRIPTION
szclient es un pequeño programa que permite la simulacion de el poke-safari en consola.
.SH OPTIONS
No Hay opciones adicionales
.SH SEE ALSO
szserver(6)
.SH BUGS
No hay conocidos
.SH AUTHOR
(diegofavela@.ciencias.unam.mx, 777coatl@ciencias.unam.mx, fernandofong@ciencias.unam.mx)
